[package]
name = "crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
age.workspace = true
chacha20poly1305.workspace = true
